// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpmdszhwlgdqswtlozgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwbWRzemh3bGdkcXN3dGxvemdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTg0NjgsImV4cCI6MjA2MjM3NDQ2OH0.fz1U-mwIHggUuBKQHbqDP_wihtntMEEFBzN1oDzPB1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);